import Head from "next/head";
import Image from "next/image";
import Nav from "@/components/Nav";
import TV from "../assests/tv.png";
import Lewis from "../assests/lewis.png";
import Kids from "../assests/kids.png";
import Mobile from "../assests/mobile.jpg";
import { PlusIcon } from "@heroicons/react/24/solid";
import { useState } from "react";
import { questions } from "../../questions";
import FAQs from "@/components/FAQs";
import Footer from "@/components/Footer";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { selectUser } from "../../slices/userSlice";
import { useEffect } from "react";
import { useLocalStorage } from "usehooks-ts";

export default function Home() {
  const router = useRouter();
  const user = useSelector(selectUser);
  const [email, setEmail] = useLocalStorage("useremail", "");

function proceedSignup(event) {
  event.preventDefault();
  router.push('/signup')
}

  return (
    <>
      <div className="  from-black bg-[url('/bgimage.png')] h-[70vh] sm:h-[100vh] w-full  bg-cover bg-center bg-no-repeat  ">
        <main className="p-5 ">
          <Head>
            <title>Netflix Clone</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/logoxsm.png" />
          </Head>

          <Nav />
          <div className="text-white flex flex-col items-center mt-20 sm:mt-[200px] text-center space-y-3">
            <h1 className="text-[28px] sm:text-[40px] lg:text-[50px] font-[700]">
              Unlimited movies, TV shows and more.
            </h1>
            <p className="sm:text-[20px] lg:text-[26px] ">
              Watch anywhere. Cancel at any time.
            </p>
            <p className="sm:text-[20px]  lg:text-[26px]">
              {" "}
              {user ? (
                <>Let&apos;s go</>
              ) : (
                <>
                  Ready to watch Netflix? Enter your email to create or restart
                  your membership
                </>
              )}
            </p>
            <div className="flex flex-col space-y-3 sm:flex-row sm:space-y-0">
             
              {user ? (
                <>
                  {" "}
                  <button
                    onClick={() => router.push("/browse")}
                    className="bg-NetflixRed h-10 sm:h-12 px-3 w-[150px] m-auto"
                  >
                    {" "}
                    Start Watching &#62;
                  </button>{" "}
                </>
              ) : (
                <>
                <form onSubmit={proceedSignup}>
                  <input
                    onChange={(event) => setEmail(event.target.value)}
                    placeholder="Email address"
                    type="email"
                    required
                    className=" outline-none h-10 sm:h-12 w-[300px] text-black p-2"
                  ></input>
                  <button onClick={proceedSignup}
                    
                    className="bg-NetflixRed h-10 sm:h-12 px-3 w-[150px] m-auto"
                  >
                    {" "}
                    Get Started &#62;
                  </button>
                  </form>
                </>
              )}
            </div>
          </div>
        </main>
      </div>

      {/* Description */}

      <div className="sm:flex sm:flex-col sm:items-center md:flex md:flex-row md:items-center  md:justify-center border-t-[10px]  border-white border-opacity-20  bg-black text-white text-center md:text-start md:space-x-2 px-5 sm:px-12 py-14 sm:pt-5">
        <div className="space-y-4 sm:space-y-0 sm:max-w-[450px]  sm:flex sm:flex-col">
          <h1 className="text-smallh1   sm:text-mediumh1 lg:text-largeh1 font-[700]">
            Enjoy Netflix on your TV.
          </h1>
          <p className=" text-smalldescription sm:text-mediumdescription  lg:text-largedescription">
            {" "}
            Watch titles on Smart TVs, PlayStation, Xbox, Chromecast, Apple TV,
            Blu-ray players and more.
          </p>
        </div>
        <div>
          <Image src={TV} width={640} height={480} alt="tv" />
        </div>
      </div>

      <div className="sm:flex sm:flex-col sm:items-center md:flex md:flex-row-reverse md:items-center  md:justify-center border-t-[10px]  border-white border-opacity-20  bg-black text-white text-center md:text-start md:space-x-2 px-5 sm:px-12 py-14 sm:pt-5">
        <div className="space-y-4 sm:space-y-0 sm:max-w-[450px]  sm:flex sm:flex-col md:ml-5">
          <h1 className="text-smallh1   sm:text-mediumh1 lg:text-largeh1 font-[700]">
            Watch Netflix everywhere
          </h1>
          <p className=" text-smalldescription sm:text-mediumdescription  lg:text-largedescription">
            {" "}
            Stream unlimited movies and TV shows on your phone, tablet, laptop
            and TV without paying more
          </p>
        </div>
        <div>
          <Image src={Lewis} width={640} height={480} alt="tv" />
        </div>
      </div>

      <div className="sm:flex sm:flex-col sm:items-center md:flex md:flex-row md:items-center  md:justify-center border-t-[10px]  border-white border-opacity-20  bg-black text-white text-center md:text-start md:space-x-2 px-5 sm:px-12 py-14 sm:pt-5">
        <div className="space-y-4 sm:space-y-0 sm:max-w-[450px]  sm:flex sm:flex-col md:mt-10">
          <h1 className="text-smallh1   sm:text-mediumh1 lg:text-largeh1 font-[700]">
            Create profile for kids.
          </h1>
          <p className=" text-smalldescription sm:text-mediumdescription  lg:text-largedescription">
            Send kids on adventures with their favourite characters in a space
            made just for them free with your membership{" "}
          </p>
        </div>
        <div>
          <Image src={Kids} width={640} height={480} alt="tv" />
        </div>
      </div>

      <div className="sm:flex sm:flex-col sm:items-center md:flex md:flex-row-reverse md:items-center  md:justify-center border-t-[10px]  border-white border-opacity-20  bg-black text-white text-center md:text-start md:space-x-2 px-5 sm:px-12 py-14 sm:pt-5">
        <div className="space-y-4 sm:space-y-0 sm:max-w-[450px]  sm:flex sm:flex-col ">
          <h1 className="text-smallh1   sm:text-mediumh1 lg:text-largeh1 font-[700]">
            Download your shows to watch them offline
          </h1>
          <p className=" text-smalldescription sm:text-mediumdescription  lg:text-largedescription">
            {" "}
            Only available on ad-free plans
          </p>
        </div>
        <div>
          <Image src={Mobile} width={640} height={480} alt="tv" />
        </div>
      </div>

      {/*  FREQUENTLY ASEKD QUESTIONS*/}
      <div className="bg-black text-white border-t-[10px] border-opacity-20 border-white p-4 pt-8 flex flex-col items-center ">
        <h1 className="text-smallh1 font-[700] md:text-mediumh1 lg:text-largeh1 text-center">
          Frequently Asked Questions{" "}
        </h1>
        <div className="space-y-2 sm:w-3/4 lg:w-1/2 m-auto mt-8">
          {questions.map((question) => (
            <FAQs key={question.id} item={question} />
          ))}
        </div>
      </div>

      {/* READY TO WATCH NETFLIX? */}
      <div className="bg-black text-white flex flex-col items-center space-y-4 py-12">
        <h1 className="text-smalldescription text-center">
          Ready to watch Netflix? Enter your email to create or restart your
          membership.{" "}
        </h1>
        <div className="flex flex-col space-y-2 sm:flex-row sm:items-center sm:space-y-0">
          <form onSubmit={proceedSignup}>
          <input
            onChange={(event) => setEmail(event.target.value)}
            placeholder="Email address"
            type="email"
            className=" outline-none h-10 sm:h-12 w-[300px] text-black p-2"
          ></input>
          <button
            onClick={proceedSignup}
            className="bg-NetflixRed h-10 sm:h-12 px-3 w-[150px] m-auto"
          >
            {" "}
            Get Started &#62;
          </button>
          </form>
        </div>
      </div>

      {/* FOOTER */}
      <Footer />
    </>
  );
}
