import Head from "next/head";
import Image from "next/image";
import Nav from "@/components/Nav";
import TV from "../assests/tv.png"

export default function Home() {
  return (
    <>
      <div className="  from-black bg-[url('/bgimage.png')] h-[70vh] sm:h-[100vh] w-full  bg-cover bg-center bg-no-repeat  ">
        <main className="p-5 ">
          <Head>
            <title>Netflix Clone</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/logoxsm.png" />
          </Head>

          <Nav />
          <div className="text-white flex flex-col items-center mt-20 sm:mt-[200px] text-center space-y-3">
            <h1 className="text-[28px] sm:text-[40px] lg:text-[50px] font-[700]">
              Unlimited movies, TV shows and more.
            </h1>
            <p className="sm:text-[20px] lg:text-[26px] ">
              Watch anywhere. Cancel at any time.
            </p>
            <p className="sm:text-[20px]  lg:text-[26px]">
              {" "}
              Ready to watch Netflix? Enter your email to create or restart your
              membership
            </p>
            <div className="flex flex-col space-y-3 sm:flex-row sm:space-y-0">
              <input className=" outline-none h-10 sm:h-12 w-[300px]"></input>
              <button className="bg-NetflixRed h-10 sm:h-12 px-3 w-[150px] m-auto">
                {" "}
                Get Started &#62;
              </button>
            </div>
          </div>
        </main>
      </div>

      {/* Description */}

      <div className=" sm:flex sm:items-center  sm:justify-center border-t-[10px] border-gray-700 bg-black text-white text-center sm:text-start px-5 sm:px-12 pt-10 sm:pt-5" >
        <div className="space-y-4 sm:space-y-0 sm:max-w-[450px]  sm:flex sm:flex-col">
        <h1 className= "text-smallh1   sm:text-mediumh1 md:text-largeh1 font-[600]">Enjoy Netflix on your TV.</h1>
        <p className=" text-smalldescription sm:text-mediumdescription  md:text-largedescription"> Watch titles on Smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.</p>
     </div>
     <div>
      <Image src={TV}  width={640} height={480} alt='tv' />
      

     </div>
      </div>
    </>
  );
}
