import Head from "next/head";
import { useRouter } from "next/router"
import { useEffect } from "react"

function Search() {
  const router = useRouter();


  useEffect(() => {
    router.push('/')

    
  })
  return (
    <div>
      <Head>
            <title>Search</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/logoxsm.png" />
          </Head>
    </div>
  )
}
export default Search